Removed the redundant code
praveenscience/react-shopping-cart-helper pull request #1
Opened 2020-09-27 12:24 UTC by annu12340

2020-09-27 19:24 UTC, praveenscience requested changes
Small changes. 😊

2020-09-27 19:24 UTC, praveenscience commented on src/components/App.js
> +      setSelectedItems([...SelectedItems, key];
We need a `.sort()`, but the callback function is not necessary.

2020-09-27 19:24 UTC, praveenscience commented on src/components/App.js
> +      const idx = items.indexOf(key)
`;` missing.

2020-09-28 05:58 UTC, annu12340 commented on src/components/App.js
> +      const idx = items.indexOf(key)
Oh!
My bad :grimacing:

2020-09-28 10:45 UTC, praveenscience approved these changes
Looks good to me! 👍🏻

2020-09-28 10:45 UTC, merged